export enum ActionType {
	ADD_COORDINATES = 'ADD_COORDINATES',
    ADD_CITY_WEATHER = 'ADD_CITY_WEATHER',
    ADD_CITIES_WEATHER = 'ADD_CITIES_WEATHER',
    ADD_LOCAL_CURRENT_WEATHER = 'ADD_LOCAL_CURRENT_WEATHER',
}
