export enum ActionType {
    ADD_CITY_WEATHER = 'ADD_CITY_WEATHER',
    ADD_CITIES_WEATHER = 'ADD_CITIES_WEATHER',
    ADD_LOCAL_CURRENT_WEATHER = 'ADD_LOCAL_CURRENT_WEATHER',
    ADD_THREE_HOURS_WEATHER = 'ADD_THREE_HOURS_WEATHER',
    ADD_LOCAL_THREE_HOURS_WEATHER = 'ADD_LOCAL_THREE_HOURS_WEATHER',
    ADD_ALL_THREE_HOURS_WEATHER = 'ADD_ALL_THREE_HOURS_WEATHER',
}
